
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: server01
    steps:
      - uses: actions/checkout@v4

      - name: copy data to document root
        run: cp -rvf * /var/www/html
        
      - name: Run a one-line script
        run: echo Hello, world2 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
